Feat: Chat-141-레이아웃-작성-날짜별-채팅
Chat-Diary/FE pull request #13
Opened 2024-01-09 15:13 UTC by somin-jeong

## 요약 (Summary)
채팅 화면에서 날짜별 채팅 선택하는 다이얼로그 레이아웃 작성

## 변경 사항 (Changes)
## 리뷰 요구사항
## 확인 방법 (선택)

<img width="304" alt="image" src="https://github.com/Chat-Diary/FE/assets/81250561/f20f6900-3096-4d47-b96a-f9b4a0cb7fc8">

2024-01-10 05:18 UTC, Nangniya commented
확인

2024-01-10 05:20 UTC, Nangniya approved these changes
확인

2024-01-11 05:17 UTC, nonaninona requested changes

2024-01-11 05:17 UTC, nonaninona commented on src/assets/index.ts
> +export { ReactComponent as Plus } from './icons/plus.svg';
커밋 메시지
Feat (대문자)로 바꿔주세요 🤭

2024-01-11 05:26 UTC, Nangniya commented
확인

2024-01-11 05:26 UTC, merged