Feat: Chat-169-태그-정렬-바텀시트-레이아웃-작성
Chat-Diary/FE pull request #29
Opened 2024-01-19 16:31 UTC by somin-jeong

## 요약 (Summary)
태그 화면 정렬 선택 다이얼로그 바텀시트 레이아웃 작성

## 변경 사항 (Changes)
- 모든 다이얼로그 띄우는 화면에서 스크롤 막음

## 리뷰 요구사항

## 확인 방법 (선택)

<img width="363" alt="image" src="https://github.com/Chat-Diary/FE/assets/81250561/9a95f732-84de-4dd2-9776-aed70c68cd5b">

2024-01-19 16:43 UTC, Nangniya requested changes

2024-01-19 16:43 UTC, Nangniya commented on src/components/Buttons/SortChangeRadioBtn.tsx
> +interface IProps {
IProps 잘 쓰고 있는것같아서 좋네요

2024-01-19 16:43 UTC, Nangniya commented on src/pages/Chat/Chat.tsx
> +
이건 왜한건가요

2024-01-19 16:45 UTC, somin-jeong commented on src/pages/Chat/Chat.tsx
> +
다이얼로그 띄워졌을때 화면에서 스크롤 안되게 막은거에요!

2024-01-19 16:58 UTC, Nangniya commented on src/pages/Chat/Chat.tsx
> +
이거 다이얼로그 쓰는 컴포넌트에서 일일이 다 안해도 다이얼로그 컴포넌트에서 useEffect 똑같이 써도 적용돼요

2024-01-19 16:59 UTC, Nangniya commented on src/pages/Chat/Chat.tsx
> +
Chat.tsx에서 지우고 DateSelector에 옮겨서 해봤는데 스크롤 안돼여

2024-01-19 17:00 UTC, somin-jeong commented on src/pages/Chat/Chat.tsx
> +
오 수정할게영

2024-01-20 06:10 UTC, Nangniya approved these changes

2024-01-20 06:10 UTC, Nangniya commented on src/components/BottomSheets/BottomModal.tsx
> +
바꾼거 굿

2024-01-20 06:10 UTC, Nangniya commented on src/components/BottomSheets/BottomModal.tsx
> +      <div className={styles.BottomContainer}>{children}</div>
props. 안쓰고 destructure 문법쓴거 좋아요

2024-01-20 06:10 UTC, Nangniya commented on src/pages/Tag/Tag.tsx
> +  }, [isSelectedSorted]);
이것도 TagSoltModal에서 한번만 해도 될거같아요

2024-01-20 06:12 UTC, merged