Feat: Chat-153-일기-리스트-api-연동
Chat-Diary/FE pull request #48
Opened 2024-02-02 09:20 UTC by somin-jeong

## 요약 (Summary)
일기 리스트 api 연동

## 변경 사항 (Changes)
바텀시트로 날짜 선택하면 setCurrentDate로 날짜 설정해줌

## 리뷰 요구사항

## 확인 방법 (선택)
<img width="374" alt="image" src="https://github.com/Chat-Diary/FE/assets/81250561/ef430e56-a7d2-4989-a088-3ad5f54d49ba">

2024-02-02 20:32 UTC, nonaninona reviewed
리뷰는 못하겠어서(react 잘 몰라서 너무 오래걸림 ㅋㅋ..) 버그 제보만 합니다~
캘린더랑 연관된 내용이라 누가 담당해야할 지는 모르겠어여~

1. 캘린더 화면에서 날짜 변경시 한 달 전 API를 요청하네요
근데 24년 2월 달은 그 전달인 1월 달을 불러왔는데도 잘 뜨네요

정확하게 발생조건을 말하자면
처음에 home 접근했을 때는 24년 2월 API가 날아감 ->
날짜를 24년 1월로 바꾸면 23년 12월 API가 날아감(캘린더에 아무 점도 안 뜸 떠야하는데) ->
날짜를 다시 24년 2월로 바꾸면 24년 1월 API가 날아감(근데 캘린더에는 제대로 뜸 아마 react query가 캐싱해서?? 잘 모르겠네요)

2. 리스트에서는 날짜 변경시 제대로 된 날짜로 잘 불러옵니다. 다만 화면 깜빡임이 심한데 캘린더에서는 안그래서 무슨 차이가 있나 싶습니다.

2024-02-03 08:07 UTC, Nangniya commented
> 리뷰는 못하겠어서(react 잘 몰라서 너무 오래걸림 ㅋㅋ..) 버그 제보만 합니다~ 캘린더랑 연관된 내용이라 누가 담당해야할 지는 모르겠어여~
> 
> 1. 캘린더 화면에서 날짜 변경시 한 달 전 API를 요청하네요
>    근데 24년 2월 달은 그 전달인 1월 달을 불러왔는데도 잘 뜨네요
> 
> 정확하게 발생조건을 말하자면 처음에 home 접근했을 때는 24년 2월 API가 날아감 -> 날짜를 24년 1월로 바꾸면 23년 12월 API가 날아감(캘린더에 아무 점도 안 뜸 떠야하는데) -> 날짜를 다시 24년 2월로 바꾸면 24년 1월 API가 날아감(근데 캘린더에는 제대로 뜸 아마 react query가 캐싱해서?? 잘 모르겠네요)
> 
> 2. 리스트에서는 날짜 변경시 제대로 된 날짜로 잘 불러옵니다. 다만 화면 깜빡임이 심한데 캘린더에서는 안그래서 무슨 차이가 있나 싶습니다.

첫번째는 currentDate는 useState로 관리하는데 formattedDate는 그냥 const 변수라서 currentDate 바뀌면 업데이트가 같이 안돼서 그런거같아서 수정해보겠습니다.

2024-02-03 08:23 UTC, Nangniya requested changes

2024-02-03 08:23 UTC, Nangniya commented on src/pages/Chat/Chat.tsx
> +  const { weekCalendarList, currentDate, setCurrentDate } = useCalendar();
Chat에서는 해당 날짜가 있는 채팅 위치로 스크롤 이동하는거라... 방법은 저도 잘 모르겠지만 
useCalendar를 쓰는건 아닐거에요
Chat은 일단 그대로 둡시다

2024-02-03 08:23 UTC, Nangniya commented on src/pages/Home/Home.tsx
> +    setCurrentDate(new Date(year as number, (month as number) - 1));
이거 주의할점이 as number를 쓰면 숫자로 실제로 바꿔주는게아니라 숫자로 취급해주겟다 이런  의미라 연산을 하면 제대로 안될거에요 -1하면 마이너스 제대로 해 주긴 하는데 +를 하면 '123' as number + 1 하면 '1231' 이렇게 출력됩니다

2024-02-03 08:23 UTC, Nangniya commented
Chat에서 충돌나는데 충돌 해결하고 merge하면 제가 버그 해결해보겠습니다

2024-02-04 06:35 UTC, Nangniya approved these changes

2024-02-04 06:35 UTC, merged